[build-system]
requires = ["setuptools>=40.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "kamodo_ccmc"
version = "26.08.5"
description = "Reader ecosystem for Kamodo scientific data functionalization"
readme = "README.md"
authors = [
    { name = "Darren De Zeeuw", email = "darren.dezeeuw@nasa.gov" }
]
license = { text = "NASA OPEN SOURCE AGREEMENT VERSION 1.3" }
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
    "License :: OSI Approved"
]
dependencies = [
    "kamodo-core-official",
    "numpy",
    "pandas",
    "netCDF4",
    "nbformat",
    "cdflib",
    "astropy",
    "h5py",
    "sgp4",
    "hapiclient",
    "spacepy",
    "s3fs",
    "boto3",
    "h5netcdf",
    "psutil",
    "rbamlib",
    "pyverbplt>=24.9",
    "plotly",
    "numba"
]

[project.urls]
Repository = "https://github.com/nasa/Kamodo"
Documentation = "https://nasa.github.io/Kamodo"

[tool.setuptools]
include-package-data = true
packages = [
    "kamodo_ccmc",
    "kamodo_ccmc.readers",
    "kamodo_ccmc.tools",
    "kamodo_ccmc.flythrough",
    "kamodo_ccmc.readers.OCTREE_BLOCK_GRID",
    "kamodo_ccmc.readers.Tri2D",
    "kamodo_ccmc.readers.OpenGGCM",
    "kamodo_ccmc.libs"
]

[tool.pytest.ini_options]
filterwarnings = [
    "ignore:'asyncio\\.iscoroutinefunction' is deprecated:DeprecationWarning",
    "ignore:Could not infer format, so each element will be parsed individually:UserWarning",
    "ignore:Setting the shape on a NumPy array has been deprecated:DeprecationWarning",
    "ignore:__array__ implementation doesn't accept a copy keyword:DeprecationWarning",
    "ignore:numpy.ndarray size changed, may indicate binary incompatibility:RuntimeWarning"
]

[tool.distutils.bdist_wheel]
py-limited-api = "cp310"

[tool.cibuildwheel]
build = "cp310-*"
skip = "*-win32 *-manylinux_i686 *-musllinux_* pp*"
test-command = "python -c \"import kamodo_ccmc; print('OK')\""

[tool.cibuildwheel.linux]
before-all = "yum install -y gcc-gfortran || (apt-get update && apt-get install -y gfortran)"
manylinux-x86_64-image = "manylinux2014"
manylinux-aarch64-image = "manylinux2014"

[tool.cibuildwheel.windows]
before-build = "pip install delvewheel"
repair-wheel-command = "delvewheel repair -w {dest_dir} {wheel}"

